#!/bin/sh

# cleanup
rm -rf 0bj_dir
rm -f controlnew.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace Sign-extension.sv --exe controlnew_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vcontrolnew.mk Vcontrolnew

# run executable simulation file
obj_dir/Vcontrolnew