#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f sign_ext.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace sign_ext.sv --exe sign_ext_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir -f Vsign_ext.mk Vsign_ext

# run executable simulation file
obj_dir/Vsign_ext