#!/bin/sh

# cleanup
rm -rf 0bj_dir
rm -f cpu.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace ALU.sv top.sv data_mem_mux.sv instr_mem.sv main.sv pc.sv register.sv Signextension.sv --exe top_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

# run executable simulation file
obj_dir/Vcpu