#!/bin/sh

# cleanup
rm -rf 0bj_dir
rm -f ALU.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace data_mem_mux.sv --exe ALU_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VALU.mk VALU

# run executable simulation file
obj_dir/VALU